<Project>
  <PropertyGroup>
    <GameDir Condition="'$(GameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\MindOverMagic</GameDir>
    <GameManagedDir>$(GameDir)\mindovermagic_Data\Managed</GameManagedDir>
    <BepInExCoreDir>$(GameDir)\BepInEx\core</BepInExCoreDir>
  </PropertyGroup>
</Project>

