"""Generate Archmage Progression's status YAML.

Run from the repository root after changing the definitions below:

    python scripts/generate_archmage_content.py

The plugin fills every {Token} in descriptions, and every numeric effect value,
from its BepInEx config at load time, so numbers here are placeholders. Powers a
player disables in the config are stripped from the definitions at load too.
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "ArchmageAscension" / "Content" / "CharacterStatus"

# (internal skill, stat keyword for the per-level bonus, or None for prose)
SCHOOLS = [
    ("Pyromancy", "MaxMana"),
    ("Geomancy", "MaxHP"),
    ("Divination", "CombatStat_DamageBonus"),
    ("Manipulation", "CombatStat_DodgeChance"),
    ("Hydrokinesis", None),
    ("Necromancy", None),
    ("Viturgy", "Mood"),
]

RANKS = [
    ("Adept", "{school} Adept", "Has trained <slink=Skill_{school}> to level {{Threshold}} or higher.",
     "The fundamentals are second nature now."),
    ("Archmage", "Archmage of {school}", "Has mastered <slink=Skill_{school}> at level {{Threshold}} or higher.",
     "Few living mages have walked this far down the path."),
]

# Native effects carried by a rank. Archmage includes the Adept power, so both get it.
RANK_EFFECTS = {
    ("Pyromancy", "Adept"): ["  WorkProgressModifiers:", "  - JobType: Cook", "    ModifierPercentage: 1",
                             "  BattleChildStatuses: [{ Key: Counterattack }]"],
    ("Pyromancy", "Archmage"): ["  WorkProgressModifiers:", "  - JobType: Cook", "    ModifierPercentage: 1",
                                "  BattleChildStatuses: [{ Key: Counterattack }]"],
    ("Manipulation", "Archmage"): ["  StatusEffects: [GhostMovement]"],
    ("Geomancy", "Adept"): ["  BattleChildStatuses: [{ Key: ArchmageProgression_EarthBulwark }]"],
    ("Geomancy", "Archmage"): ["  BattleChildStatuses: [{ Key: ArchmageProgression_EarthBulwark }]"],
    ("Necromancy", "Adept"): ["  FloatVariables:", "    HPGainOnEnemyDeath: 0"],
    ("Necromancy", "Archmage"): ["  FloatVariables:", "    HPGainOnEnemyDeath: 0"],
}

NATURE_EMBRACE_LEVELS = 20
COUNCIL_BADGE_LEVELS = 40
ATTUNEMENT_LEVELS = 12


def benefit(school, link):
    if school == "Hydrokinesis":
        return ("Each <slink=Skill_Hydrokinesis> level grants +{PerLevel} combat regeneration, "
                "at least +{MinBonus} at this rank.")
    if school == "Necromancy":
        return ("Each <slink=Skill_Necromancy> level slows ordinary need decay by {PerLevel}, "
                "at least {MinBonus} at this rank.")
    return (f"Each <slink=Skill_{school}> level grants +{{PerLevel}} <slink={link}>, "
            f"at least +{{MinBonus}} at this rank.")


def header(lines):
    return ["# GENERATED by scripts/generate_archmage_content.py. Edit the script, not this file."] + lines + [""]


def status(key, display, name, description, extra=(), flavor=None, log=False, hours=None):
    out = [
        f"- Id: {{ Key: {key} }}",
        f"  DisplayType: {display}",
        "  DisplayName:",
        f"    Text: \"{name}\"",
        f"    Key: Mod.{key}.DisplayName",
        "  Description:",
        f"    Text: \"{description}\"",
        f"    Key: Mod.{key}.Description",
    ]
    if flavor:
        out += ["  FlavorText:", f"    Text: {flavor}", f"    Key: Mod.{key}.FlavorText"]
    if log:
        out += ["  LogCategory: Notice", "  LogString:", "    Text: \"{0} earned the title of {1}\"",
                f"    Key: Mod.{key}.LogString"]
    out += ["  ShownInGroupRules: false", "  Beneficial: true"]
    out += [f"  DurationInGameHours: {hours}"] if hours else ["  Persistent: true"]
    out += ["  KeepOnAdultify: true"]
    out += list(extra)
    return out + [""]


def mood(bias_placeholder="0"):
    return ["  NeedRateChanges:", "  - NeedsType: Mood", f"    TargetBias: {bias_placeholder}"]


def write(name, lines):
    (OUT / name).write_text("\n".join(lines), encoding="utf-8", newline="\n")


def ranks():
    lines = header([
        "# Rank badges. DisplayType Alert puts them in the selected-mage summary under the",
        "# portrait; Alert raises neither the red '!!' (Emergency only) nor a top-left alert",
        "# (AlertData only). {Powers} becomes the rank's power text, or nothing.",
    ])
    for school, link in SCHOOLS:
        for rank, name, reached, flavor in RANKS:
            key = f"ArchmageProgression_{school}_{rank}"
            text = f"{reached.format(school=school)} {benefit(school, link)}{{Powers}}"
            lines += status(key, "Alert", name.format(school=school), text,
                            RANK_EFFECTS.get((school, rank), ()), flavor=flavor, log=True)
    # Battle-start armour for Earth ranks, modelled on the base game's BattleArmor1_Battle.
    lines += status(
        "ArchmageProgression_EarthBulwark", "None", "Stone Bulwark",
        "Adds {Percent} of <slink=MaxHP> as <slink=TempHP> on battle start.",
        ["  BattleIcon: Armor", "  BattleString:", "    Text: Armor",
         "    Key: Mod.ArchmageProgression_EarthBulwark.BattleString",
         "  ClearAfterBattle: true", "  PercentArmorChangeOnAdd: 0.5", "  ShowLargeIcon: true"])
    # Fire Archmage renewal: a visible reward and a hidden once-a-day cooldown. The plugin sets
    # both durations and the Conviction bias from its config.
    lines += status(
        "ArchmageProgression_FireRenewed", "Info", "Renewed by Flame",
        "Flame burned away an old wound or scar. +{Bonus} <slink=Mood> target.",
        mood(), hours=24)
    lines += status(
        "ArchmageProgression_FireRenewalCooldown", "None", "Renewal Gathering",
        "The flame is gathering strength to burn away another wound or scar.", hours=24)
    write("archmage_ranks.yaml", lines)


def attunement():
    lines = header([
        "# Viturgy's per-level Conviction bias: one status per level. DisplayType Info keeps it",
        "# out of the summary; the Status & Conviction panel lists any Mood need-rate change.",
    ])
    for level in range(1, ATTUNEMENT_LEVELS + 1):
        lines += status(
            f"ArchmageProgression_ViturgyAttunement_{level}", "Info", "Viturgy Attunement",
            "Training in <slink=Skill_Viturgy> steadies the mind. Level {Level} at +{PerLevel} "
            "per level: +{Bonus} <slink=Mood> target.",
            mood())
    write("viturgy_attunement.yaml", lines)


def school_wide():
    lines = header([
        "# School-wide effects. Embrace of Nature: one status per number of Archmages of",
        "# Viturgy a mage benefits from. Council effects go on every mage; the founder carries",
        "# one Alert badge per Archmage count whose tooltip lists the powers in force.",
    ])
    for count in range(1, NATURE_EMBRACE_LEVELS + 1):
        lines += status(
            f"ArchmageProgression_NatureEmbrace_{count}", "Info", "Embrace of Nature",
            "{Count} Archmage(s) of <slink=Skill_Viturgy> share their calm: +{Bonus} <slink=Mood> target.",
            mood())
    lines += status(
        "ArchmageProgression_CouncilEffect_Conviction", "Info", "Archmage Council: Resolve",
        "The school's Archmage Council steadies every mage: +{Bonus} <slink=Mood> target.",
        mood())
    # Scholarship is two statuses. The game totals a lesson's bonuses in one table keyed by
    # status: the student's learning bonuses first, then the teacher's teaching bonuses. A
    # single status carrying both would be added twice when one Council mage teaches
    # another, which crashes the simulation.
    lines += status(
        "ArchmageProgression_CouncilEffect_Scholarship", "Info", "Archmage Council: Scholarship",
        "The Archmage Council speeds study: teaching and learning are {Percent} faster.",
        ["  SkillProgressModifiers:", "  - Skill: None", "    ModifierAmount: 1",
         "    Conditions:", "    - Condition: Learning",
         "  WorkProgressModifiers:", "  - JobType: Learn", "    ModifierPercentage: 1"])
    lines += status(
        "ArchmageProgression_CouncilEffect_ScholarshipTeach", "None", "Archmage Council: Scholarship",
        "The Archmage Council speeds teaching: lessons are {Percent} more effective.",
        ["  TeachBonusPct: 1"])
    for count in range(1, COUNCIL_BADGE_LEVELS + 1):
        shown = f"{count}+" if count == COUNCIL_BADGE_LEVELS else str(count)
        lines += status(
            f"ArchmageProgression_CouncilBadge_{count}", "Alert", f"Archmage Council ({shown})",
            "The school holds {Count} Archmage rank(s).{Powers}",
            flavor="Reality means little when the Archmages gather their power.")
    write("school_powers.yaml", lines)


NEXUS_GATEWAY = """# GENERATED by scripts/generate_archmage_content.py. Edit the script, not this file.
# A buildable copy of the Underschool's native Nexus Gateway (Nexus_Teleporter_Door):
# same model and teleport pathing, plus construction and shop configs modelled on the
# Broom Rack. The plugin keeps it out of the build menu until the school has an Archmage
# of Geomancy. Built gateways teleport to each other and to discovered Underschool ones.
- EntityKey: { Key: ArchmageProgression_NexusGateway }
  Codex:
    Tags:
      - { Key: Archetype }
      - { Key: Buildable }
      - { Key: Furniture }
  Configs:
  - !DescriptionConfig
    DisplayName:
      Text: Nexus Gateway
      Key: Mod.ArchmageProgression_NexusGateway.DisplayName
    Description:
      Text: Teleports to any other Nexus Gateway. Only an Archmage of Earth can raise one.
      Key: Mod.ArchmageProgression_NexusGateway.Description
    FlavorText:
      Text: The bones of the world remember every road.
      Key: Mod.ArchmageProgression_NexusGateway.FlavorText
  - !PlacementConfig
    Size: {X: 3, Y: 5, Z: 1}
    BlockingFlags: None
    PlacementFlags: Room,Floor,AllowBeyondZPlacement
    DefaultRotation: 180
  - !CellUseConfig {}
  - !AssembleCraftedErrandConfig
    Inputs:
      { Key: Stone }: 120
      { Key: Metal }: 40
      { Key: ManaCrystal }: 2
    CastsRequired: 30
    FlatpackEntityKey: { Key: Flatpack }
  - !ShopConfig
    Category: { Key: Furniture }
    SubCategory: { Key: SchoolTraversal }
  - !DisassembleCraftedErrandConfig {}
  - !DisintegrateCraftedErrandConfig {}
  - !RenderConfig
    PrefabKey: Environment/Dungeons/Nexus/Decor/NexusTeleporterDoor_1x3x6
    WorldRootPath: Furniture
    PlacementPivotLocation: Bottom
    UIUseGameobjectAttachPoint: true
  - !PriorityConfig {}
  - !AllowedGroupsConfig
    UniqueId: 0
    DefaultGroups: [AllStaff, AllStudents, AllHelpers]
    IncludeStaff: true
    IncludeStudents: true
    IncludeNone: true
    IncludeIndividuals: true
    IncludeStudentBatches: true
    IncludeFactions: true
    IncludeConjured: true
    NoPlayerControl: true
  - !ExtraPathingDataConfig
    ProvidesStandardPathing: true
    ExtraPathingData:
""" + "".join(f"""      {{X: {x}, Y: -2, Z: 0}}:
        FastTravelType: Teleport
        FastTravelDir: Both
        FastTravelEnterTimeSeconds: 0
        FastTravelExitTimeSeconds: 0
        FastTravelSpeedModifier: -1
        ValidPathDirections:
        - [Right]
        - [Left]
        - [Forward]
""" for x in (-1, 0, 1)) + """  - !FastTravelStationConfig
    FastTravelType: Teleport
    StartAvailable: 1000000
"""


# Waters of Return: a ritual fountain reusing the native Water Apprentice Fountain
# (WaterClassStation) model, size, ritual sequence and RitualBucketA anchor points. Its one
# Basic ritual revives the mage buried in a grave in the same room; the plugin checks the
# target, performs the revival on completion, and hides the fountain from the build menu
# until the school has an Archmage of Hydrokinesis.
RITUAL_POINTS = "".join(f"""      - Offset: {{X: {x}, Z: {z}}}
        SelectionBias: {bias}
""" for x, z, bias in [(2.5, -.5, 2), (2.5, .5, 2), (-2.5, -.5, 2), (-2.5, .5, 2),
                       (.5, -2.5, 2), (-.5, -2.5, 2), (.5, 2.5, 1), (-.5, 2.5, 1)])

WATERS_OF_RETURN = """# GENERATED by scripts/generate_archmage_content.py. Edit the script, not this file.
- EntityKey: { Key: ArchmageProgression_WatersOfReturn }
  Codex:
    Tags:
      - { Key: Archetype }
      - { Key: Buildable }
      - { Key: Furniture }
  Configs:
  - !CompositeConfig
    Category: Tables
  - !DescriptionConfig
    DisplayName:
      Text: Waters of Return
      Key: Mod.ArchmageProgression_WatersOfReturn.DisplayName
    Description:
      Text: A fountain whose waters reach past the grave. Its ritual raises the mage buried in a grave in the same room. Only an Archmage of Water can perform it.
      Key: Mod.ArchmageProgression_WatersOfReturn.Description
    FlavorText:
      Text: The water of life remembers every name.
      Key: Mod.ArchmageProgression_WatersOfReturn.FlavorText
  - !PlacementConfig
    Size: {X: 4, Y: 6, Z: 4}
    BlockingFlags: Standard
    PlacementFlags: Room,Floor,Outside,Ground
    DefaultRotation: 90
  - !RitualSiteConfig
    UniqueId: 1
    RitualType: Basic
    SequenceId: ApprenticeRitualWater
    Icon: Rituals/RitualIcons/Basic
    CustomMageCacheId: Basic
    SimMinutes: 240
    StartRitualAudioEvent: Play_EVENT_DefaultRitual
    StopRitualAudioEvent: PLAY_APPRENTICERITUAL_WATER
    WindowAmbienceStateValue: RITUAL_ORACULUM_WINDOW
    NotShownInResearchUI: true
    ButtonName:
      Text: Waters of Return
      Key: Mod.ArchmageProgression_WatersOfReturn.Ritual.ButtonName
    ButtonDescription:
      Text: Raise the mage buried in a grave in this room.
      Key: Mod.ArchmageProgression_WatersOfReturn.Ritual.ButtonDescription
    WindowDescription:
      Text: |
        An Archmage of Water calls a buried mage back through the fountain's waters. The fountain and the grave must share a room. The mage returns with their skills, level and appearance, but their badges, likes, relationships, relics and lasting effects stay behind in the grave.
      Key: Mod.ArchmageProgression_WatersOfReturn.Ritual.WindowDescription
    Inputs:
      { Key: ManaCrystal }: 1
      { Key: PhoenixFlower }: 50
      { Key: GnosisShards }: 54
    Buckets:
    - Name:
        Text: Archmage of Water
        Key: Mod.ArchmageProgression_WatersOfReturn.Ritual.Officiant
      InteractionPoint: RitualBucketA
      MinNeeded: 1
      MaxAllowed: 1
      RitualBucketAnimType: RitualSlotA
      AppliedStatuses:
      - { Key: PerformedRitual }
      DrainMana: true
      Requirements:
        RequiredComponent: Model.CharacterComponent
        RequiredStatuses: [{ Key: ArchmageProgression_Hydrokinesis_Archmage }]
      BucketPrefab: PositionMarkers/RitualSlot_01_A
      BucketIcon: RitualSlot_A
      BucketPositions:
      - {X: 0, Z: -3.5}
      BucketUniqueId: 0
  - !RitualSiteBookOfRitualsEntityConfig
    BookOfRitualsSortMetric: 36
    SingleEntryStyle: true
    BookOfRitualsDescription:
      Text: A fountain raised by an Archmage of Water, whose waters can carry a buried mage back to the living.
      Key: Mod.ArchmageProgression_WatersOfReturn.BookDescription
  - !CellUseConfig {}
  - !InteractionPointsConfig
    InteractionPoints:
      RitualBucketA:
""" + RITUAL_POINTS + """  - !AssembleCraftedErrandConfig
    Inputs:
      { Key: Stone }: 40
      { Key: IcePetal }: 20
      { Key: Bile }: 20
    CastsRequired: 100
    FlatpackEntityKey: { Key: Flatpack }
  - !ShopConfig
    Category: { Key: Furniture }
    SubCategory: { Key: Furniture_RitualsAndRelics }
  - !DisassembleCraftedErrandConfig {}
  - !DisintegrateCraftedErrandConfig {}
  - !RenderConfig
    PrefabKey: Furniture/Teaching/Water/WaterTeachingStation_4x4x2
    ShopPrefabKey: Shop/Furniture/Teaching/Water/WaterTeachingStation_4x4x2_Shop
    WorldRootPath: Furniture
    PlacementPivotLocation: Bottom
    ShowBounds: true
    UIOffset: {Y: 3}
  - !DurabilityConfig
    MaxDurability: 100
  - !PriorityConfig {}
"""


def nexus():
    entities = OUT.parent / "Entities"
    entities.mkdir(parents=True, exist_ok=True)
    (entities / "nexus_gateway.yaml").write_text(NEXUS_GATEWAY, encoding="utf-8", newline="\n")
    (entities / "waters_of_return.yaml").write_text(WATERS_OF_RETURN, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    ranks()
    attunement()
    school_wide()
    nexus()
    print(f"Wrote status YAML to {OUT}")
